<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            [
                'name' => 'Netflix 1 Bulan Sharing',
                'description' => 'Akun Netflix sharing durasi 1 bulan dengan garansi penuh.',
                'price' => 30000,
                'duration' => '1 Bulan',
                'warranty' => '1 Bulan',
                'stock' => 50,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Netflix 3 Bulan Sharing',
                'description' => 'Akun Netflix sharing durasi 3 bulan.',
                'price' => 80000,
                'duration' => '3 Bulan',
                'warranty' => '2 Bulan',
                'stock' => 50,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Youtube Premium 1 Bulan Invite',
                'description' => 'Youtube Premium via family invite 1 bulan.',
                'price' => 25000,
                'duration' => '1 Bulan',
                'warranty' => '1 Bulan',
                'stock' => 100,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Youtube Premium 3 Bulan Invite',
                'description' => 'Youtube Premium via family invite 3 bulan.',
                'price' => 60000,
                'duration' => '3 Bulan',
                'warranty' => '3 Bulan',
                'stock' => 100,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Spotify Premium 1 Bulan Individual',
                'description' => 'Spotify premium legal 1 bulan perpanjang akun sendiri.',
                'price' => 20000,
                'duration' => '1 Bulan',
                'warranty' => '1 Bulan',
                'stock' => 200,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Spotify Premium 3 Bulan Individual',
                'description' => 'Spotify premium legal 3 bulan perpanjang akun sendiri.',
                'price' => 55000,
                'duration' => '3 Bulan',
                'warranty' => '3 Bulan',
                'stock' => 150,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Canva Pro 1 Bulan Invite',
                'description' => 'Canva Pro invite via email 1 bulan.',
                'price' => 10000,
                'duration' => '1 Bulan',
                'warranty' => '1 Bulan',
                'stock' => 500,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Canva Pro 1 Tahun Invite',
                'description' => 'Canva Pro invite via email 1 tahun.',
                'price' => 50000,
                'duration' => '12 Bulan',
                'warranty' => '12 Bulan',
                'stock' => 200,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Disney+ Hotstar 1 Bulan Private',
                'description' => 'Akun Private Disney+ 1 Bulan',
                'price' => 45000,
                'duration' => '1 Bulan',
                'warranty' => '1 Bulan',
                'stock' => 30,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Disney+ Hotstar 3 Bulan Private',
                'description' => 'Akun Private Disney+ 3 Bulan',
                'price' => 120000,
                'duration' => '3 Bulan',
                'warranty' => '3 Bulan',
                'stock' => 30,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Vidio Premier Platinum 1 Bulan',
                'description' => 'Akun Vidio Platinum 1 Bulan Private.',
                'price' => 35000,
                'duration' => '1 Bulan',
                'warranty' => '1 Bulan',
                'stock' => 40,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Vidio Premier Platinum 1 Tahun',
                'description' => 'Akun Vidio Platinum 1 Tahun Private.',
                'price' => 250000,
                'duration' => '12 Bulan',
                'warranty' => '12 Bulan',
                'stock' => 20,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Prime Video 1 Bulan Private',
                'description' => 'Akun Prime Video 1 Bulan Private.',
                'price' => 30000,
                'duration' => '1 Bulan',
                'warranty' => '1 Bulan',
                'stock' => 60,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ChatGPT Plus 1 Bulan Sharing',
                'description' => 'Akun ChatGPT Plus Sharing 1 Bulan.',
                'price' => 90000,
                'duration' => '1 Bulan',
                'warranty' => '1 Bulan',
                'stock' => 15,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'NordVPN 1 Tahun Sharing',
                'description' => 'Akun NordVPN Premium Sharing 1 Tahun.',
                'price' => 40000,
                'duration' => '12 Bulan',
                'warranty' => '6 Bulan',
                'stock' => 200,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('products')->insert($products);
    }
}
